In [71]:
import requests 
import pandas as pd 
import numpy as np
import json
import time 
import os 
from pathlib import Path

In [72]:
os.makedirs("data/raw", exist_ok=True)
COUNTRIES = [
    "KEN", "TZA", "UGA", "ETH", "MOZ",       # East Africa
    "NGA", "GHA", "CIV", "SEN",               # West Africa
    "EGY", "MAR", "TUN",                      # North Africa
    "ZAF", "BWA", "ZMB",                      # Southern Africa
    "USA", "GBR", "DEU", "FRA", "JPN",        # Major advanced
    "CHN", "IND", "BRA", "MEX", "IDN",        # Large EM (IDN not TUR twice)
    "TUR", "THA", "MYS", "PHL", "VNM",        # Asia EM
    "SAU", "ARE", "NOR", "AUS", "CAN",        # Commodity exporters ← comma here
    "POL", "CZE", "HUN", "ROU",               # Eastern Europe
    "ARG", "CHL", "COL", "PER",               # Latin America
    "KOR", "SGP", "PAK", "BGD",              # Other Asia ← comma here
    "ISL", "NZL", "CRI",                      # Small open economies
]
INDICATORS= {
    "NY.GDP.MKTP.KD.ZG": "gdp_growth",
    "FP.CPI.TOTL.ZG": "inflation",
    "SL.UEM.TOTL.ZS": "unemployment",
    "FR.INR.LEND": "lending_rate",
    "NE.TRD.GNFS.ZS": "trade_opennes",
    "BN.CAB.XOKA.GD.ZS": "govt_debt",
    "NY.GDP.PCAP.KD.ZG": "gdp_per_capita_growth"
}

START_YEAR= 1995
END_YEAR=2023
# RAW_PATH = Path(r"data/raw/wb_raw.csv")
# PROCESSED_PATH=Path(r"data/processed/panel.csv")
# TENSOR_PATH= Path(r"data/processed/tensor.npy")
# META_PATH = Path(r"data/processed/metadata.json")

In [73]:
def fetch_indicator(code, name, countries ,start_year,end_year):
    country_str=";".join(countries)
    url=(
        f"https://api.worldbank.org/v2/country/{country_str}/indicator/{code}?date={start_year}:{end_year}&format=json&per_page=10000"
    )
    resp=requests.get(url,timeout=30)
    resp.raise_for_status()
    payload=resp.json()
        
    if not isinstance(payload,list):
        print(f"Unexpected response for {code}: {payload}")
        return pd.DataFrame()
    if len(payload) < 2 or not payload[1]:
        print(f"Unexpected response for {code}: {payload}")
        print(f" Raw response: {payload[0]}")
        return pd.DataFrame()

    records=[
        {
            "country_iso3":item["countryiso3code"],
            "country_name": item["country"]["value"],
            "year": int(item["date"]),
            name: item["value"]
        }
        for item in payload[1]
    ]
    return pd.DataFrame(records)

panel=None

for code,name in INDICATORS.items():
    print(f"Fetching: {name}...")
    df= fetch_indicator(code,name,COUNTRIES,START_YEAR,END_YEAR)
    panel= df if panel is None else panel.merge(
        df[["country_iso3","year",name]],
        on=["country_iso3","year"],
        how="outer"

    )
    time.sleep(0.5)

panel = panel.sort_values(["country_iso3","year"]).reset_index(drop=True)

panel.to_csv("data/raw/wb_panel_raw.csv", index=False)

print(f"\nShape: {panel.shape}")
print(f"Countries: {panel['country_iso3'].nunique()}")
print(f"Years: {panel["year"].min()} - {panel['year'].max()}")

print("\n --- Missing Value Per Column-----")
for col in list(INDICATORS.values()):
    n= panel[col].isna().sum()
    pct= panel[col].isna().mean() * 100
    print(f" {col:<28} {n:>5} missing ({pct:.1f}%)")

print("\n--- Kenya rows(all years)--------")
print(panel[panel["country_iso3"]=="KEN"].to_string(index=False))
print("\nSaved")

Fetching: gdp_growth...
Fetching: inflation...
Fetching: unemployment...
Fetching: lending_rate...
Fetching: trade_opennes...
Fetching: govt_debt...
Fetching: gdp_per_capita_growth...

Shape: (1450, 10)
Countries: 50
Years: 1995 - 2023

 --- Missing Value Per Column-----
 gdp_growth                       0 missing (0.0%)
 inflation                       47 missing (3.2%)
 unemployment                     0 missing (0.0%)
 lending_rate                   422 missing (29.1%)
 trade_opennes                   51 missing (3.5%)
 govt_debt                       57 missing (3.9%)
 gdp_per_capita_growth            0 missing (0.0%)

--- Kenya rows(all years)--------
country_iso3 country_name  year  gdp_growth  inflation  unemployment  lending_rate  trade_opennes  govt_debt  gdp_per_capita_growth
         KEN        Kenya  1995    4.406217   1.554328         2.848     28.795833      71.745742 -17.446216               1.483737
         KEN        Kenya  1996    4.146839   8.864087         2.773     33.786667      57.312111  -7.979416               1.319006
         KEN        Kenya  1997    0.474902  11.361845         2.818     30.245000      54.057117 -13.652802              -2.233663
         KEN        Kenya  1998    3.290214   6.722437         2.843     29.490000      48.897242 -18.679824               0.478811
         KEN        Kenya  1999    2.305389   5.742001         2.884     22.380000      48.192275 -18.340704              -0.603258
         KEN        Kenya  2000    0.599695   9.980025         2.884     22.339167      53.309044  -1.569352              -2.386107
         KEN        Kenya  2001    3.779906   5.738598         2.876     19.665833      55.946836  -2.466323               0.575577
         KEN        Kenya  2002    0.546860   1.961308         2.916     18.453333      55.172672  -0.894976              -2.567363
         KEN        Kenya  2003    2.932476   9.815691         2.869     16.573333      54.132266   0.888450              -0.194798
         KEN        Kenya  2004    5.104300  11.624036         2.844     12.531667      59.477003  -0.818703               1.891135
         KEN        Kenya  2005    5.906666  10.312778         2.739     12.882500      64.478866  -1.346558               2.702441
         KEN        Kenya  2006    6.472494  14.453734         2.673     13.635534      55.236485  -1.976470               3.277155
         KEN        Kenya  2007    6.850730   9.758880         2.642     13.340344      53.894789  -3.229370               3.669787
         KEN        Kenya  2008    0.232283  26.239817         2.751     14.016939      57.578599  -5.523296              -2.758865
         KEN        Kenya  2009    3.306940   9.234126         2.816     14.804541      45.945192  -3.987289               0.232598
         KEN        Kenya  2010    8.058474   3.961389         2.793     14.371500      50.394287  -5.216694               4.968113
         KEN        Kenya  2011    5.121106  14.022491         2.699     15.046760      58.402206  -8.148809               2.269522
         KEN        Kenya  2012    4.568680   9.377770         2.678     19.723407      51.623692  -7.475872               1.876708
         KEN        Kenya  2013    3.797848   5.717494         2.762     17.313458      47.464643  -7.851522               1.263311
         KEN        Kenya  2014    5.020111   6.878155         2.767     16.513931      46.170489  -9.340049               2.592184
         KEN        Kenya  2015    4.967721   6.582154         2.762     16.086614      40.327385  -6.304597               2.655894
         KEN        Kenya  2016    4.213517   6.297250         2.757     16.559631      34.865020  -5.397009               1.937948
         KEN        Kenya  2017    3.837958   8.005650         3.542     13.667573      35.995058  -6.996833               1.604752
         KEN        Kenya  2018    5.647946   4.689806         4.284     13.060759      34.414753  -5.411067               3.524048
         KEN        Kenya  2019    5.114159   5.239638         5.014     12.441133      31.759462  -5.238529               3.070048
         KEN        Kenya  2020   -0.272766   5.405162         5.613     11.995785      30.399139  -3.269110              -2.210322
         KEN        Kenya  2021    7.590489   6.107936         5.693     12.079998      35.002048  -4.599008               5.565137
         KEN        Kenya  2022    4.859981   7.659863         5.565     12.335841      40.275324  -4.199953               2.862813
         KEN        Kenya  2023    5.719992   7.671396         5.409     13.588502      41.111090  -2.545525               3.644255

Saved

In [74]:
missing_by_country=(
    panel.groupby("country_iso3")[["lending_rate","trade_opennes", "govt_debt", "inflation"]]
    .apply(lambda g: g.isna().mean() *100).round(1)
)
print(missing_by_country[missing_by_country["lending_rate"]> 0]. sort_values("lending_rate",ascending=False))

              lending_rate  trade_opennes  govt_debt  inflation
country_iso3
ARE                  100.0           20.7       96.6       44.8
FRA                  100.0            0.0        0.0        0.0
TUN                  100.0            0.0        0.0        0.0
DEU                  100.0            0.0        0.0        0.0
MAR                  100.0            0.0        0.0        0.0
GHA                  100.0            0.0        0.0        0.0
POL                  100.0            0.0        0.0        0.0
TUR                  100.0            0.0        0.0        0.0
SAU                  100.0            0.0        0.0        0.0
NOR                   62.1            0.0        0.0        0.0
SEN                   58.6            0.0        0.0        0.0
CIV                   58.6            0.0       34.5        0.0
ARG                   51.7            0.0        0.0       79.3
ETH                   51.7           55.2        0.0        0.0
PAK                   37.9            0.0        0.0        0.0
NZL                   31.0            0.0       17.2        0.0
GBR                   31.0            0.0        0.0        0.0
JPN                   20.7            0.0        3.4        0.0
CAN                   20.7            0.0        0.0        0.0
CHL                   17.2            0.0        0.0        0.0
UGA                   17.2            0.0        0.0        0.0
PHL                   13.8            0.0        0.0        0.0
AUS                   13.8            0.0        0.0        0.0
TZA                   10.3            0.0        0.0        0.0
ZMB                   10.3            0.0        6.9        0.0
BRA                    6.9            0.0        0.0        0.0
USA                    6.9            0.0        0.0        0.0
THA                    6.9            0.0        0.0        0.0
MOZ                    6.9            0.0       34.5       34.5
SGP                    6.9            0.0        0.0        0.0
KOR                    3.4            0.0        0.0        0.0
IND                    3.4            0.0        0.0        0.0
PER                    3.4            0.0        0.0        0.0
VNM                    3.4            0.0        3.4        3.4

In [75]:
missing_by_country = (
    panel.groupby("country_iso3")[list(INDICATORS.values())]
    .apply(lambda g: g.isna().sum())
)

In [76]:
panel= panel.drop(columns=["lending_rate"])

In [77]:
panel.columns

Index(['country_iso3', 'country_name', 'year', 'gdp_growth', 'inflation',
       'unemployment', 'trade_opennes', 'govt_debt', 'gdp_per_capita_growth'],
      dtype='str')

In [78]:
panel.isna().sum()

country_iso3              0
country_name              0
year                      0
gdp_growth                0
inflation                47
unemployment              0
trade_opennes            51
govt_debt                57
gdp_per_capita_growth     0
dtype: int64

In [79]:
panel["country_name"].unique()

<StringArray>
['United Arab Emirates',            'Argentina',            'Australia',
           'Bangladesh',               'Brazil',             'Botswana',
               'Canada',                'Chile',                'China',
        'Cote d'Ivoire',             'Colombia',           'Costa Rica',
              'Czechia',              'Germany',     'Egypt, Arab Rep.',
             'Ethiopia',               'France',       'United Kingdom',
                'Ghana',              'Hungary',            'Indonesia',
                'India',              'Iceland',                'Japan',
                'Kenya',          'Korea, Rep.',              'Morocco',
               'Mexico',           'Mozambique',             'Malaysia',
              'Nigeria',               'Norway',          'New Zealand',
             'Pakistan',                 'Peru',          'Philippines',
               'Poland',              'Romania',         'Saudi Arabia',
              'Senegal',            'Singapore',             'Thailand',
              'Tunisia',              'Turkiye',             'Tanzania',
               'Uganda',        'United States',             'Viet Nam',
         'South Africa',               'Zambia']
Length: 50, dtype: str

In [80]:
panel.isna().groupby(panel["country_name"]).sum()

,country_iso3,country_name,year,gdp_growth,inflation,unemployment,trade_opennes,govt_debt,gdp_per_capita_growth
country_name,,,,,,,,,
Argentina,0,0,0,0,23,0,0,0,0
Australia,0,0,0,0,0,0,0,0,0
Bangladesh,0,0,0,0,0,0,0,0,0
Botswana,0,0,0,0,0,0,0,0,0
Brazil,0,0,0,0,0,0,0,0,0
Canada,0,0,0,0,0,0,0,0,0
Chile,0,0,0,0,0,0,0,0,0
China,0,0,0,0,0,0,0,0,0
Colombia,0,0,0,0,0,0,0,0,0
Costa Rica,0,0,0,0,0,0,0,0,0
Cote d'Ivoire,0,0,0,0,0,0,0,10,0
Czechia,0,0,0,0,0,0,0,0,0
"Egypt, Arab Rep.",0,0,0,0,0,0,0,0,0
Ethiopia,0,0,0,0,0,0,16,0,0
France,0,0,0,0,0,0,0,0,0
Germany,0,0,0,0,0,0,0,0,0
Ghana,0,0,0,0,0,0,0,0,0
Hungary,0,0,0,0,0,0,0,0,0
Iceland,0,0,0,0,0,0,0,0,0
India,0,0,0,0,0,0,0,0,0
Indonesia,0,0,0,0,0,0,0,0,0
Japan,0,0,0,0,0,0,0,1,0
Kenya,0,0,0,0,0,0,0,0,0
"Korea, Rep.",0,0,0,0,0,0,0,0,0
Malaysia,0,0,0,0,0,0,0,0,0
Mexico,0,0,0,0,0,0,0,0,0
Morocco,0,0,0,0,0,0,0,0,0
Mozambique,0,0,0,0,10,0,0,10,0
New Zealand,0,0,0,0,0,0,0,5,0
Nigeria,0,0,0,0,0,0,29,0,0
Norway,0,0,0,0,0,0,0,0,0
Pakistan,0,0,0,0,0,0,0,0,0
Peru,0,0,0,0,0,0,0,0,0
Philippines,0,0,0,0,0,0,0,0,0
Poland,0,0,0,0,0,0,0,0,0
Romania,0,0,0,0,0,0,0,0,0
Saudi Arabia,0,0,0,0,0,0,0,0,0
Senegal,0,0,0,0,0,0,0,0,0
Singapore,0,0,0,0,0,0,0,0,0
South Africa,0,0,0,0,0,0,0,0,0
Tanzania,0,0,0,0,0,0,0,0,0
Thailand,0,0,0,0,0,0,0,0,0
Tunisia,0,0,0,0,0,0,0,0,0
Turkiye,0,0,0,0,0,0,0,0,0
Uganda,0,0,0,0,0,0,0,0,0
United Arab Emirates,0,0,0,0,13,0,6,28,0
United Kingdom,0,0,0,0,0,0,0,0,0
United States,0,0,0,0,0,0,0,0,0
Viet Nam,0,0,0,0,1,0,0,1,0
Zambia,0,0,0,0,0,0,0,2,0

In [81]:
panel1=panel.copy()
panel1[panel1["country_name"]=="Rwanda"]

Empty DataFrame
Columns: [country_iso3, country_name, year, gdp_growth, inflation, unemployment, trade_opennes, govt_debt, gdp_per_capita_growth]
Index: []

In [82]:
DROP = [
    "ARG",  # missing 2023 inflation + hyperinflation distortion
    "ARE",  # 28 govt debt, 13 inflation, 6 trade openness
    "NGA",  # 29 trade openness — structural reporting problem
    "ETH",  # 16 trade openness
    "CIV",  # 10 govt debt
    "RWA",  # only starts 2009 — too short
]
panel=panel[~panel["country_iso3"].isin(DROP)].reset_index(drop=True)

print(f"Shape: {panel.shape}")

Shape: (1305, 9)

In [84]:
panel

,country_iso3,country_name,year,gdp_growth,inflation,unemployment,trade_opennes,govt_debt,gdp_per_capita_growth
0,AUS,Australia,1995,3.890172,4.627764,8.473,37.646874,-5.063186,2.739531
1,AUS,Australia,1996,3.865675,2.615379,8.509,38.174021,-3.583603,2.612517
2,AUS,Australia,1997,3.917958,0.224895,8.367,37.921701,-2.729749,2.799586
3,AUS,Australia,1998,4.676814,0.860130,7.684,39.924066,-4.441118,3.638646
4,AUS,Australia,1999,5.028220,1.483139,6.876,38.960247,-5.583664,3.885499
...,...,...,...,...,...,...,...,...,...
1300,ZMB,Zambia,2019,1.441306,9.150316,5.538,68.791205,0.603691,-1.518950
1301,ZMB,Zambia,2020,-2.785055,15.733060,6.032,79.206849,11.790957,-5.567735
1302,ZMB,Zambia,2021,6.234922,22.020768,5.197,86.208511,11.900351,3.285755
1303,ZMB,Zambia,2022,5.211224,10.993204,5.993,69.297315,3.747847,2.343365
1304,ZMB,Zambia,2023,5.367943,10.884532,5.861,78.241887,-3.037510,2.464640

#### PRE-PROCESSING